/*
 * Qualpay Platform API
 * This document describes the Qualpay Platform API.
 *
 * OpenAPI spec version: 1.1.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AccountUpdaterSummaryReport
 */

public class AccountUpdaterSummaryReport {
  @SerializedName("request_id")
  private Long requestId = null;

  @SerializedName("merchant_id")
  private Long merchantId = null;

  /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 16 AN&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Status of the request. The status can be one of the following               &lt;ul&gt;              &lt;li&gt;QUEUED - Account updater request is queued in the Account updater service&lt;/li&gt;              &lt;li&gt;COMPLETED - Account updater request has completed&lt;/li&gt;              &lt;/ul&gt;
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    QUEUED("QUEUED"),
    
    COMPLETED("COMPLETED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("cnt_request")
  private Integer cntRequest = null;

  @SerializedName("cnt_response")
  private Integer cntResponse = null;

  @SerializedName("cnt_update")
  private Integer cntUpdate = null;

  @SerializedName("request_date")
  private String requestDate = null;

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 10 N&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Unique ID assigned by Qualpay to the account updater request.
   * @return requestId
  **/
  @ApiModelProperty(example = "112", value = "<strong>Format: </strong>Variable length, up to 10 N<br><strong>Description: </strong>Unique ID assigned by Qualpay to the account updater request.")
  public Long getRequestId() {
    return requestId;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 16 N&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Unique ID assigned by Qualpay to a Merchant.
   * @return merchantId
  **/
  @ApiModelProperty(example = "212000000001", value = "<strong>Format: </strong>Variable length, up to 16 N<br><strong>Description: </strong>Unique ID assigned by Qualpay to a Merchant.")
  public Long getMerchantId() {
    return merchantId;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 16 AN&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Status of the request. The status can be one of the following               &lt;ul&gt;              &lt;li&gt;QUEUED - Account updater request is queued in the Account updater service&lt;/li&gt;              &lt;li&gt;COMPLETED - Account updater request has completed&lt;/li&gt;              &lt;/ul&gt;
   * @return status
  **/
  @ApiModelProperty(example = "QUEUED", value = "<strong>Format: </strong>Variable length, up to 16 AN<br><strong>Description: </strong>Status of the request. The status can be one of the following               <ul>              <li>QUEUED - Account updater request is queued in the Account updater service</li>              <li>COMPLETED - Account updater request has completed</li>              </ul>")
  public StatusEnum getStatus() {
    return status;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 10 N&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Number of cards in this request.
   * @return cntRequest
  **/
  @ApiModelProperty(example = "145", value = "<strong>Format: </strong>Variable length, up to 10 N<br><strong>Description: </strong>Number of cards in this request.")
  public Integer getCntRequest() {
    return cntRequest;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 10 N&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Number of cards in this request that were reviewed by the account updater service. (This should match the cnt_request.). The cnt_response field will be zero if the status field is not COMPLETED.
   * @return cntResponse
  **/
  @ApiModelProperty(example = "145", value = "<strong>Format: </strong>Variable length, up to 10 N<br><strong>Description: </strong>Number of cards in this request that were reviewed by the account updater service. (This should match the cnt_request.). The cnt_response field will be zero if the status field is not COMPLETED.")
  public Integer getCntResponse() {
    return cntResponse;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 10 N&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Number of cards in this request that were updated by the account updater service. The cnt_update field will be zero if the status field is not COMPLETED or if there are no updates by the account updater service.
   * @return cntUpdate
  **/
  @ApiModelProperty(example = "25", value = "<strong>Format: </strong>Variable length, up to 10 N<br><strong>Description: </strong>Number of cards in this request that were updated by the account updater service. The cnt_update field will be zero if the status field is not COMPLETED or if there are no updates by the account updater service.")
  public Integer getCntUpdate() {
    return cntUpdate;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 10 AN, in  YYYY-MM-DD format&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Account updater request date. Date when a harvest request was sent to the account updater service.
   * @return requestDate
  **/
  @ApiModelProperty(example = "2017-05-06", value = "<strong>Format: </strong>Variable length, up to 10 AN, in  YYYY-MM-DD format<br><strong>Description: </strong>Account updater request date. Date when a harvest request was sent to the account updater service.")
  public String getRequestDate() {
    return requestDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountUpdaterSummaryReport accountUpdaterSummaryReport = (AccountUpdaterSummaryReport) o;
    return Objects.equals(this.requestId, accountUpdaterSummaryReport.requestId) &&
        Objects.equals(this.merchantId, accountUpdaterSummaryReport.merchantId) &&
        Objects.equals(this.status, accountUpdaterSummaryReport.status) &&
        Objects.equals(this.cntRequest, accountUpdaterSummaryReport.cntRequest) &&
        Objects.equals(this.cntResponse, accountUpdaterSummaryReport.cntResponse) &&
        Objects.equals(this.cntUpdate, accountUpdaterSummaryReport.cntUpdate) &&
        Objects.equals(this.requestDate, accountUpdaterSummaryReport.requestDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestId, merchantId, status, cntRequest, cntResponse, cntUpdate, requestDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountUpdaterSummaryReport {\n");
    
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    merchantId: ").append(toIndentedString(merchantId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    cntRequest: ").append(toIndentedString(cntRequest)).append("\n");
    sb.append("    cntResponse: ").append(toIndentedString(cntResponse)).append("\n");
    sb.append("    cntUpdate: ").append(toIndentedString(cntUpdate)).append("\n");
    sb.append("    requestDate: ").append(toIndentedString(requestDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

