/*
 * Qualpay Platform API
 * This document describes the Qualpay Platform API.
 *
 * OpenAPI spec version: 1.1.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AddBillingCardRequest
 */

public class AddBillingCardRequest {
  @SerializedName("card_number")
  private String cardNumber = null;

  @SerializedName("exp_date")
  private String expDate = null;

  @SerializedName("cvv2")
  private String cvv2 = null;

  @SerializedName("type_id")
  private String typeId = null;

  @SerializedName("dda_number")
  private String ddaNumber = null;

  @SerializedName("card_id")
  private String cardId = null;

  @SerializedName("billing_first_name")
  private String billingFirstName = null;

  @SerializedName("billing_last_name")
  private String billingLastName = null;

  @SerializedName("billing_firm_name")
  private String billingFirmName = null;

  @SerializedName("billing_addr1")
  private String billingAddr1 = null;

  @SerializedName("billing_addr2")
  private String billingAddr2 = null;

  @SerializedName("billing_city")
  private String billingCity = null;

  @SerializedName("billing_state")
  private String billingState = null;

  @SerializedName("billing_zip")
  private String billingZip = null;

  @SerializedName("billing_zip4")
  private String billingZip4 = null;

  @SerializedName("billing_country")
  private String billingCountry = null;

  @SerializedName("billing_country_code")
  private String billingCountryCode = null;

  @SerializedName("verify")
  private Boolean verify = null;

  @SerializedName("primary")
  private Boolean primary = null;

  @SerializedName("merchant_id")
  private Long merchantId = null;

  @SerializedName("tr_number")
  private String trNumber = null;

  public AddBillingCardRequest cardNumber(String cardNumber) {
    this.cardNumber = cardNumber;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 16 AN&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;The full card number.  When a card is added, it is immediately tokenized and a card_id is generated and stored in vault.  Duplicate cards are not permitted for a customer in the system &lt;br&gt;&lt;strong&gt;Conditional Requirement: &lt;/strong&gt; A card_number or card_id  is required when adding a billing card. 
   * @return cardNumber
  **/
  @ApiModelProperty(example = "4111111111111111", value = "<strong>Format: </strong>Variable length, up to 16 AN<br><strong>Description: </strong>The full card number.  When a card is added, it is immediately tokenized and a card_id is generated and stored in vault.  Duplicate cards are not permitted for a customer in the system <br><strong>Conditional Requirement: </strong> A card_number or card_id  is required when adding a billing card. ")
  public String getCardNumber() {
    return cardNumber;
  }

  public void setCardNumber(String cardNumber) {
    this.cardNumber = cardNumber;
  }

  public AddBillingCardRequest expDate(String expDate) {
    this.expDate = expDate;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Fixed length, 4 N, MMYY format&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Expiration date of cardholder card number. &lt;br&gt;&lt;strong&gt;Conditional Requirement: &lt;/strong&gt; The exp_date is required if card_number field is present.
   * @return expDate
  **/
  @ApiModelProperty(example = "0420", value = "<strong>Format: </strong>Fixed length, 4 N, MMYY format<br><strong>Description: </strong>Expiration date of cardholder card number. <br><strong>Conditional Requirement: </strong> The exp_date is required if card_number field is present.")
  public String getExpDate() {
    return expDate;
  }

  public void setExpDate(String expDate) {
    this.expDate = expDate;
  }

  public AddBillingCardRequest cvv2(String cvv2) {
    this.cvv2 = cvv2;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 4 N&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;CVV2 or CID value from the signature panel on the back of the cardholder&#39;s card. If present during a request where the verify flag is set to true, the value will be sent to the issuer for validation. This field will not be stored in customer vault.
   * @return cvv2
  **/
  @ApiModelProperty(example = "152", value = "<strong>Format: </strong>Variable length, up to 4 N<br><strong>Description: </strong>CVV2 or CID value from the signature panel on the back of the cardholder's card. If present during a request where the verify flag is set to true, the value will be sent to the issuer for validation. This field will not be stored in customer vault.")
  public String getCvv2() {
    return cvv2;
  }

  public void setCvv2(String cvv2) {
    this.cvv2 = cvv2;
  }

  public AddBillingCardRequest typeId(String typeId) {
    this.typeId = typeId;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Fixed length, 1 AN&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Bank Account Type. Applicable for ACH account numbers. Possible values are: &lt;ul&gt;&lt;li&gt;C &#x3D; Personal checking account&lt;/li&gt;&lt;li&gt;S &#x3D; Personal savings account&lt;/li&gt;&lt;li&gt;K &#x3D; Business checking account&lt;/li&gt;&lt;li&gt;V &#x3D; Business savings account&lt;/li&gt;&lt;/ul&gt;&lt;br&gt;&lt;strong&gt;Default: &lt;/strong&gt;C
   * @return typeId
  **/
  @ApiModelProperty(example = "S", value = "<strong>Format: </strong>Fixed length, 1 AN<br><strong>Description: </strong>Bank Account Type. Applicable for ACH account numbers. Possible values are: <ul><li>C = Personal checking account</li><li>S = Personal savings account</li><li>K = Business checking account</li><li>V = Business savings account</li></ul><br><strong>Default: </strong>C")
  public String getTypeId() {
    return typeId;
  }

  public void setTypeId(String typeId) {
    this.typeId = typeId;
  }

  public AddBillingCardRequest ddaNumber(String ddaNumber) {
    this.ddaNumber = ddaNumber;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 17 N&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Owner&#39;s account number at the bank. Applicable for ACH account numbers.&lt;br&gt;&lt;strong&gt;Conditional Requirement: &lt;/strong&gt;The tr_number and dda_number are required when adding an ACH account number.
   * @return ddaNumber
  **/
  @ApiModelProperty(example = "3456776866", value = "<strong>Format: </strong>Variable length, up to 17 N<br><strong>Description: </strong>Owner's account number at the bank. Applicable for ACH account numbers.<br><strong>Conditional Requirement: </strong>The tr_number and dda_number are required when adding an ACH account number.")
  public String getDdaNumber() {
    return ddaNumber;
  }

  public void setDdaNumber(String ddaNumber) {
    this.ddaNumber = ddaNumber;
  }

  public AddBillingCardRequest cardId(String cardId) {
    this.cardId = cardId;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Fixed length, 32 AN&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Card ID received from a tokenization request. The card_id may be used in place of a card number or card swipe. Duplicate cards are not permitted for a customer in the system. The card_id should be permanent. If a single use card_id should be used, set the verify field to true which will make the card_id permanent.&lt;br&gt;&lt;strong&gt;Conditional Requirement: &lt;/strong&gt;A card_number or card_id  is required when adding a billing card.
   * @return cardId
  **/
  @ApiModelProperty(example = "86e1b00d9b0811e68df3069d8f743581", value = "<strong>Format: </strong>Fixed length, 32 AN<br><strong>Description: </strong>Card ID received from a tokenization request. The card_id may be used in place of a card number or card swipe. Duplicate cards are not permitted for a customer in the system. The card_id should be permanent. If a single use card_id should be used, set the verify field to true which will make the card_id permanent.<br><strong>Conditional Requirement: </strong>A card_number or card_id  is required when adding a billing card.")
  public String getCardId() {
    return cardId;
  }

  public void setCardId(String cardId) {
    this.cardId = cardId;
  }

  public AddBillingCardRequest billingFirstName(String billingFirstName) {
    this.billingFirstName = billingFirstName;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 32 AN&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Billing first name. &lt;br&gt;&lt;strong&gt;Conditional Requirement: &lt;/strong&gt;Billing first name is required when adding an ACH account number.
   * @return billingFirstName
  **/
  @ApiModelProperty(example = "John", value = "<strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>Billing first name. <br><strong>Conditional Requirement: </strong>Billing first name is required when adding an ACH account number.")
  public String getBillingFirstName() {
    return billingFirstName;
  }

  public void setBillingFirstName(String billingFirstName) {
    this.billingFirstName = billingFirstName;
  }

  public AddBillingCardRequest billingLastName(String billingLastName) {
    this.billingLastName = billingLastName;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 32 AN&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Billing last name. &lt;br&gt;&lt;strong&gt;Conditional Requirement: &lt;/strong&gt;Billing last name is required when adding an ACH account number.
   * @return billingLastName
  **/
  @ApiModelProperty(example = "Doe", value = "<strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>Billing last name. <br><strong>Conditional Requirement: </strong>Billing last name is required when adding an ACH account number.")
  public String getBillingLastName() {
    return billingLastName;
  }

  public void setBillingLastName(String billingLastName) {
    this.billingLastName = billingLastName;
  }

  public AddBillingCardRequest billingFirmName(String billingFirmName) {
    this.billingFirmName = billingFirmName;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 64 AN&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Business name on billing card, if applicable. 
   * @return billingFirmName
  **/
  @ApiModelProperty(example = "Qualpay", value = "<strong>Format: </strong>Variable length, up to 64 AN<br><strong>Description: </strong>Business name on billing card, if applicable. ")
  public String getBillingFirmName() {
    return billingFirmName;
  }

  public void setBillingFirmName(String billingFirmName) {
    this.billingFirmName = billingFirmName;
  }

  public AddBillingCardRequest billingAddr1(String billingAddr1) {
    this.billingAddr1 = billingAddr1;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 128 AN&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Billing street address. This address will also be used for AVS verification if AVS verification is enabled. 
   * @return billingAddr1
  **/
  @ApiModelProperty(example = "123 Main Avenue", value = "<strong>Format: </strong>Variable length, up to 128 AN<br><strong>Description: </strong>Billing street address. This address will also be used for AVS verification if AVS verification is enabled. ")
  public String getBillingAddr1() {
    return billingAddr1;
  }

  public void setBillingAddr1(String billingAddr1) {
    this.billingAddr1 = billingAddr1;
  }

  public AddBillingCardRequest billingAddr2(String billingAddr2) {
    this.billingAddr2 = billingAddr2;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 128 AN&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Billing Address line item 2.
   * @return billingAddr2
  **/
  @ApiModelProperty(example = "#1234", value = "<strong>Format: </strong>Variable length, up to 128 AN<br><strong>Description: </strong>Billing Address line item 2.")
  public String getBillingAddr2() {
    return billingAddr2;
  }

  public void setBillingAddr2(String billingAddr2) {
    this.billingAddr2 = billingAddr2;
  }

  public AddBillingCardRequest billingCity(String billingCity) {
    this.billingCity = billingCity;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 64 AN&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Billing city.
   * @return billingCity
  **/
  @ApiModelProperty(example = "San Mateo", value = "<strong>Format: </strong>Variable length, up to 64 AN<br><strong>Description: </strong>Billing city.")
  public String getBillingCity() {
    return billingCity;
  }

  public void setBillingCity(String billingCity) {
    this.billingCity = billingCity;
  }

  public AddBillingCardRequest billingState(String billingState) {
    this.billingState = billingState;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 3 AN&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Billing state.
   * @return billingState
  **/
  @ApiModelProperty(example = "CA", value = "<strong>Format: </strong>Variable length, up to 3 AN<br><strong>Description: </strong>Billing state.")
  public String getBillingState() {
    return billingState;
  }

  public void setBillingState(String billingState) {
    this.billingState = billingState;
  }

  public AddBillingCardRequest billingZip(String billingZip) {
    this.billingZip = billingZip;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 10 AN&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Billing zip. This field will also be used for AVS verification if AVS verification is enabled.
   * @return billingZip
  **/
  @ApiModelProperty(example = "94402", required = true, value = "<strong>Format: </strong>Variable length, up to 10 AN<br><strong>Description: </strong>Billing zip. This field will also be used for AVS verification if AVS verification is enabled.")
  public String getBillingZip() {
    return billingZip;
  }

  public void setBillingZip(String billingZip) {
    this.billingZip = billingZip;
  }

  public AddBillingCardRequest billingZip4(String billingZip4) {
    this.billingZip4 = billingZip4;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Fixed length, 4 N&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Billing zip+4 code if applicable.
   * @return billingZip4
  **/
  @ApiModelProperty(example = "1234", value = "<strong>Format: </strong>Fixed length, 4 N<br><strong>Description: </strong>Billing zip+4 code if applicable.")
  public String getBillingZip4() {
    return billingZip4;
  }

  public void setBillingZip4(String billingZip4) {
    this.billingZip4 = billingZip4;
  }

  public AddBillingCardRequest billingCountry(String billingCountry) {
    this.billingCountry = billingCountry;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 128 AN&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Billing country.
   * @return billingCountry
  **/
  @ApiModelProperty(example = "United States", value = "<strong>Format: </strong>Variable length, up to 128 AN<br><strong>Description: </strong>Billing country.")
  public String getBillingCountry() {
    return billingCountry;
  }

  public void setBillingCountry(String billingCountry) {
    this.billingCountry = billingCountry;
  }

  public AddBillingCardRequest billingCountryCode(String billingCountryCode) {
    this.billingCountryCode = billingCountryCode;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Fixed length, 3 AN&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;ISO numeric country code for the billing address. Refer to &lt;a href&#x3D;\&quot;/developer/api/reference#country-codes\&quot;target&#x3D;\&quot;_blank\&quot;&gt;Country Codes&lt;/a&gt; for a list of country codes.
   * @return billingCountryCode
  **/
  @ApiModelProperty(example = "840", value = "<strong>Format: </strong>Fixed length, 3 AN<br><strong>Description: </strong>ISO numeric country code for the billing address. Refer to <a href=\"/developer/api/reference#country-codes\"target=\"_blank\">Country Codes</a> for a list of country codes.")
  public String getBillingCountryCode() {
    return billingCountryCode;
  }

  public void setBillingCountryCode(String billingCountryCode) {
    this.billingCountryCode = billingCountryCode;
  }

  public AddBillingCardRequest verify(Boolean verify) {
    this.verify = verify;
    return this;
  }

   /**
   * &lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Set this field to true if a card_number or card_id should be verified by the issuer before adding to Customer Vault. When this field is set to true, the customer will be added to vault either if the card verification successful or if card verification is not supported by the issuer.&lt;br&gt;&lt;strong&gt;Default: &lt;/strong&gt;false
   * @return verify
  **/
  @ApiModelProperty(example = "true", value = "<br><strong>Description: </strong>Set this field to true if a card_number or card_id should be verified by the issuer before adding to Customer Vault. When this field is set to true, the customer will be added to vault either if the card verification successful or if card verification is not supported by the issuer.<br><strong>Default: </strong>false")
  public Boolean isVerify() {
    return verify;
  }

  public void setVerify(Boolean verify) {
    this.verify = verify;
  }

  public AddBillingCardRequest primary(Boolean primary) {
    this.primary = primary;
    return this;
  }

   /**
   * &lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Set this field to true if this should be the default card. The default card will be used in recurring billing payments.&lt;br&gt;&lt;strong&gt;Default: &lt;/strong&gt;false
   * @return primary
  **/
  @ApiModelProperty(example = "true", value = "<br><strong>Description: </strong>Set this field to true if this should be the default card. The default card will be used in recurring billing payments.<br><strong>Default: </strong>false")
  public Boolean isPrimary() {
    return primary;
  }

  public void setPrimary(Boolean primary) {
    this.primary = primary;
  }

  public AddBillingCardRequest merchantId(Long merchantId) {
    this.merchantId = merchantId;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 16 AN&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Identifies the merchant to whom this request applies. Optional field, applicable only if the request is sent on behalf of another merchant.&lt;br&gt;&lt;strong&gt;Conditional Requirement: &lt;/strong&gt;Required if this request is on behalf of another merchant.
   * @return merchantId
  **/
  @ApiModelProperty(example = "210000000289", value = "<strong>Format: </strong>Variable length, up to 16 AN<br><strong>Description: </strong>Identifies the merchant to whom this request applies. Optional field, applicable only if the request is sent on behalf of another merchant.<br><strong>Conditional Requirement: </strong>Required if this request is on behalf of another merchant.")
  public Long getMerchantId() {
    return merchantId;
  }

  public void setMerchantId(Long merchantId) {
    this.merchantId = merchantId;
  }

  public AddBillingCardRequest trNumber(String trNumber) {
    this.trNumber = trNumber;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Fixed length, 9 N&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Bank transit/routing number. Applicable for ACH account numbers.&lt;br&gt;&lt;strong&gt;Conditional Requirement: &lt;/strong&gt; The tr_number and dda_number are required when adding an ACH account number. 
   * @return trNumber
  **/
  @ApiModelProperty(example = "011111111", value = "<strong>Format: </strong>Fixed length, 9 N<br><strong>Description: </strong>Bank transit/routing number. Applicable for ACH account numbers.<br><strong>Conditional Requirement: </strong> The tr_number and dda_number are required when adding an ACH account number. ")
  public String getTrNumber() {
    return trNumber;
  }

  public void setTrNumber(String trNumber) {
    this.trNumber = trNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddBillingCardRequest addBillingCardRequest = (AddBillingCardRequest) o;
    return Objects.equals(this.cardNumber, addBillingCardRequest.cardNumber) &&
        Objects.equals(this.expDate, addBillingCardRequest.expDate) &&
        Objects.equals(this.cvv2, addBillingCardRequest.cvv2) &&
        Objects.equals(this.typeId, addBillingCardRequest.typeId) &&
        Objects.equals(this.ddaNumber, addBillingCardRequest.ddaNumber) &&
        Objects.equals(this.cardId, addBillingCardRequest.cardId) &&
        Objects.equals(this.billingFirstName, addBillingCardRequest.billingFirstName) &&
        Objects.equals(this.billingLastName, addBillingCardRequest.billingLastName) &&
        Objects.equals(this.billingFirmName, addBillingCardRequest.billingFirmName) &&
        Objects.equals(this.billingAddr1, addBillingCardRequest.billingAddr1) &&
        Objects.equals(this.billingAddr2, addBillingCardRequest.billingAddr2) &&
        Objects.equals(this.billingCity, addBillingCardRequest.billingCity) &&
        Objects.equals(this.billingState, addBillingCardRequest.billingState) &&
        Objects.equals(this.billingZip, addBillingCardRequest.billingZip) &&
        Objects.equals(this.billingZip4, addBillingCardRequest.billingZip4) &&
        Objects.equals(this.billingCountry, addBillingCardRequest.billingCountry) &&
        Objects.equals(this.billingCountryCode, addBillingCardRequest.billingCountryCode) &&
        Objects.equals(this.verify, addBillingCardRequest.verify) &&
        Objects.equals(this.primary, addBillingCardRequest.primary) &&
        Objects.equals(this.merchantId, addBillingCardRequest.merchantId) &&
        Objects.equals(this.trNumber, addBillingCardRequest.trNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cardNumber, expDate, cvv2, typeId, ddaNumber, cardId, billingFirstName, billingLastName, billingFirmName, billingAddr1, billingAddr2, billingCity, billingState, billingZip, billingZip4, billingCountry, billingCountryCode, verify, primary, merchantId, trNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddBillingCardRequest {\n");
    
    sb.append("    cardNumber: ").append(toIndentedString(cardNumber)).append("\n");
    sb.append("    expDate: ").append(toIndentedString(expDate)).append("\n");
    sb.append("    cvv2: ").append(toIndentedString(cvv2)).append("\n");
    sb.append("    typeId: ").append(toIndentedString(typeId)).append("\n");
    sb.append("    ddaNumber: ").append(toIndentedString(ddaNumber)).append("\n");
    sb.append("    cardId: ").append(toIndentedString(cardId)).append("\n");
    sb.append("    billingFirstName: ").append(toIndentedString(billingFirstName)).append("\n");
    sb.append("    billingLastName: ").append(toIndentedString(billingLastName)).append("\n");
    sb.append("    billingFirmName: ").append(toIndentedString(billingFirmName)).append("\n");
    sb.append("    billingAddr1: ").append(toIndentedString(billingAddr1)).append("\n");
    sb.append("    billingAddr2: ").append(toIndentedString(billingAddr2)).append("\n");
    sb.append("    billingCity: ").append(toIndentedString(billingCity)).append("\n");
    sb.append("    billingState: ").append(toIndentedString(billingState)).append("\n");
    sb.append("    billingZip: ").append(toIndentedString(billingZip)).append("\n");
    sb.append("    billingZip4: ").append(toIndentedString(billingZip4)).append("\n");
    sb.append("    billingCountry: ").append(toIndentedString(billingCountry)).append("\n");
    sb.append("    billingCountryCode: ").append(toIndentedString(billingCountryCode)).append("\n");
    sb.append("    verify: ").append(toIndentedString(verify)).append("\n");
    sb.append("    primary: ").append(toIndentedString(primary)).append("\n");
    sb.append("    merchantId: ").append(toIndentedString(merchantId)).append("\n");
    sb.append("    trNumber: ").append(toIndentedString(trNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

