/*
 * Qualpay Platform API
 * This document describes the Qualpay Platform API.
 *
 * OpenAPI spec version: 1.1.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BillingCard;
import io.swagger.client.model.ShippingAddress;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * CustomerVault
 */

public class CustomerVault {
  @SerializedName("customer_id")
  private String customerId = null;

  @SerializedName("rec_id")
  private Long recId = null;

  @SerializedName("node_id")
  private Long nodeId = null;

  @SerializedName("customer_first_name")
  private String customerFirstName = null;

  @SerializedName("customer_last_name")
  private String customerLastName = null;

  @SerializedName("customer_firm_name")
  private String customerFirmName = null;

  @SerializedName("customer_phone")
  private String customerPhone = null;

  @SerializedName("customer_email")
  private String customerEmail = null;

  @SerializedName("comments")
  private String comments = null;

  @SerializedName("primary_card_number")
  private String primaryCardNumber = null;

  @SerializedName("shipping_addresses")
  private List<ShippingAddress> shippingAddresses = null;

  @SerializedName("billing_cards")
  private List<BillingCard> billingCards = null;

  public CustomerVault customerId(String customerId) {
    this.customerId = customerId;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 32 AN&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Unique ID established by merchant to identify a customer. The customer ID can be used to add subscriptions using the Recurring Billing API or make payments using the Payment Gateway API. Once established, this ID cannot be updated. This field is case sensitive. Only letters and numbers are allowed in a Customer ID.
   * @return customerId
  **/
  @ApiModelProperty(example = "JOHNDOE", value = "<strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>Unique ID established by merchant to identify a customer. The customer ID can be used to add subscriptions using the Recurring Billing API or make payments using the Payment Gateway API. Once established, this ID cannot be updated. This field is case sensitive. Only letters and numbers are allowed in a Customer ID.")
  public String getCustomerId() {
    return customerId;
  }

  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }

  public CustomerVault recId(Long recId) {
    this.recId = recId;
    return this;
  }

   /**
   * For INTERNAL USE ONLY.
   * @return recId
  **/
  @ApiModelProperty(example = "0", value = "For INTERNAL USE ONLY.")
  public Long getRecId() {
    return recId;
  }

  public void setRecId(Long recId) {
    this.recId = recId;
  }

  public CustomerVault nodeId(Long nodeId) {
    this.nodeId = nodeId;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 16 N&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;The Qualpay Merchant ID to which this customer belongs.
   * @return nodeId
  **/
  @ApiModelProperty(example = "210000000289", value = "<strong>Format: </strong>Variable length, up to 16 N<br><strong>Description: </strong>The Qualpay Merchant ID to which this customer belongs.")
  public Long getNodeId() {
    return nodeId;
  }

  public void setNodeId(Long nodeId) {
    this.nodeId = nodeId;
  }

  public CustomerVault customerFirstName(String customerFirstName) {
    this.customerFirstName = customerFirstName;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 32 AN&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Customer&#39;s first name.
   * @return customerFirstName
  **/
  @ApiModelProperty(example = "JOHN", value = "<strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>Customer's first name.")
  public String getCustomerFirstName() {
    return customerFirstName;
  }

  public void setCustomerFirstName(String customerFirstName) {
    this.customerFirstName = customerFirstName;
  }

  public CustomerVault customerLastName(String customerLastName) {
    this.customerLastName = customerLastName;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 32 AN&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Customer&#39;s last name.
   * @return customerLastName
  **/
  @ApiModelProperty(example = "Doe", value = "<strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>Customer's last name.")
  public String getCustomerLastName() {
    return customerLastName;
  }

  public void setCustomerLastName(String customerLastName) {
    this.customerLastName = customerLastName;
  }

  public CustomerVault customerFirmName(String customerFirmName) {
    this.customerFirmName = customerFirmName;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 64 AN&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Customer&#39;s business name, if applicable. 
   * @return customerFirmName
  **/
  @ApiModelProperty(example = "Qualpay", value = "<strong>Format: </strong>Variable length, up to 64 AN<br><strong>Description: </strong>Customer's business name, if applicable. ")
  public String getCustomerFirmName() {
    return customerFirmName;
  }

  public void setCustomerFirmName(String customerFirmName) {
    this.customerFirmName = customerFirmName;
  }

  public CustomerVault customerPhone(String customerPhone) {
    this.customerPhone = customerPhone;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 16 AN&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Customer&#39;s phone number.
   * @return customerPhone
  **/
  @ApiModelProperty(example = "999-999-9999", value = "<strong>Format: </strong>Variable length, up to 16 AN<br><strong>Description: </strong>Customer's phone number.")
  public String getCustomerPhone() {
    return customerPhone;
  }

  public void setCustomerPhone(String customerPhone) {
    this.customerPhone = customerPhone;
  }

  public CustomerVault customerEmail(String customerEmail) {
    this.customerEmail = customerEmail;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 64 AN&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Customer&#39;s email address. 
   * @return customerEmail
  **/
  @ApiModelProperty(example = "jdoe@qualpay.com", value = "<strong>Format: </strong>Variable length, up to 64 AN<br><strong>Description: </strong>Customer's email address. ")
  public String getCustomerEmail() {
    return customerEmail;
  }

  public void setCustomerEmail(String customerEmail) {
    this.customerEmail = customerEmail;
  }

  public CustomerVault comments(String comments) {
    this.comments = comments;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 128 AN&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Comment
   * @return comments
  **/
  @ApiModelProperty(example = "Test comment", value = "<strong>Format: </strong>Variable length, up to 128 AN<br><strong>Description: </strong>Comment")
  public String getComments() {
    return comments;
  }

  public void setComments(String comments) {
    this.comments = comments;
  }

  public CustomerVault primaryCardNumber(String primaryCardNumber) {
    this.primaryCardNumber = primaryCardNumber;
    return this;
  }

   /**
   * Default Card Number for this customer.
   * @return primaryCardNumber
  **/
  @ApiModelProperty(example = "411111xxxxxx1111", value = "Default Card Number for this customer.")
  public String getPrimaryCardNumber() {
    return primaryCardNumber;
  }

  public void setPrimaryCardNumber(String primaryCardNumber) {
    this.primaryCardNumber = primaryCardNumber;
  }

  public CustomerVault shippingAddresses(List<ShippingAddress> shippingAddresses) {
    this.shippingAddresses = shippingAddresses;
    return this;
  }

  public CustomerVault addShippingAddressesItem(ShippingAddress shippingAddressesItem) {
    if (this.shippingAddresses == null) {
      this.shippingAddresses = new ArrayList<ShippingAddress>();
    }
    this.shippingAddresses.add(shippingAddressesItem);
    return this;
  }

   /**
   * &lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;An array of shipping addresses. 
   * @return shippingAddresses
  **/
  @ApiModelProperty(value = "<br><strong>Description: </strong>An array of shipping addresses. ")
  public List<ShippingAddress> getShippingAddresses() {
    return shippingAddresses;
  }

  public void setShippingAddresses(List<ShippingAddress> shippingAddresses) {
    this.shippingAddresses = shippingAddresses;
  }

  public CustomerVault billingCards(List<BillingCard> billingCards) {
    this.billingCards = billingCards;
    return this;
  }

  public CustomerVault addBillingCardsItem(BillingCard billingCardsItem) {
    if (this.billingCards == null) {
      this.billingCards = new ArrayList<BillingCard>();
    }
    this.billingCards.add(billingCardsItem);
    return this;
  }

   /**
   * &lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;An array of billing cards. 
   * @return billingCards
  **/
  @ApiModelProperty(value = "<br><strong>Description: </strong>An array of billing cards. ")
  public List<BillingCard> getBillingCards() {
    return billingCards;
  }

  public void setBillingCards(List<BillingCard> billingCards) {
    this.billingCards = billingCards;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerVault customerVault = (CustomerVault) o;
    return Objects.equals(this.customerId, customerVault.customerId) &&
        Objects.equals(this.recId, customerVault.recId) &&
        Objects.equals(this.nodeId, customerVault.nodeId) &&
        Objects.equals(this.customerFirstName, customerVault.customerFirstName) &&
        Objects.equals(this.customerLastName, customerVault.customerLastName) &&
        Objects.equals(this.customerFirmName, customerVault.customerFirmName) &&
        Objects.equals(this.customerPhone, customerVault.customerPhone) &&
        Objects.equals(this.customerEmail, customerVault.customerEmail) &&
        Objects.equals(this.comments, customerVault.comments) &&
        Objects.equals(this.primaryCardNumber, customerVault.primaryCardNumber) &&
        Objects.equals(this.shippingAddresses, customerVault.shippingAddresses) &&
        Objects.equals(this.billingCards, customerVault.billingCards);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerId, recId, nodeId, customerFirstName, customerLastName, customerFirmName, customerPhone, customerEmail, comments, primaryCardNumber, shippingAddresses, billingCards);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerVault {\n");
    
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    recId: ").append(toIndentedString(recId)).append("\n");
    sb.append("    nodeId: ").append(toIndentedString(nodeId)).append("\n");
    sb.append("    customerFirstName: ").append(toIndentedString(customerFirstName)).append("\n");
    sb.append("    customerLastName: ").append(toIndentedString(customerLastName)).append("\n");
    sb.append("    customerFirmName: ").append(toIndentedString(customerFirmName)).append("\n");
    sb.append("    customerPhone: ").append(toIndentedString(customerPhone)).append("\n");
    sb.append("    customerEmail: ").append(toIndentedString(customerEmail)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    primaryCardNumber: ").append(toIndentedString(primaryCardNumber)).append("\n");
    sb.append("    shippingAddresses: ").append(toIndentedString(shippingAddresses)).append("\n");
    sb.append("    billingCards: ").append(toIndentedString(billingCards)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

