/*
 * Qualpay Platform API
 * This document describes the Qualpay Platform API.
 *
 * OpenAPI spec version: 1.1.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DisputeData
 */

public class DisputeData {
  @SerializedName("rec_id")
  private Long recId = null;

  @SerializedName("merchant_id")
  private Long merchantId = null;

  @SerializedName("incoming_date")
  private String incomingDate = null;

  @SerializedName("amt_tran")
  private Double amtTran = null;

  @SerializedName("amt_dispute")
  private Double amtDispute = null;

  @SerializedName("reason_code")
  private String reasonCode = null;

  @SerializedName("reason_desc")
  private String reasonDesc = null;

  @SerializedName("data_type")
  private String dataType = null;

  @SerializedName("cbr_workflow")
  private String cbrWorkflow = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("date_status_change")
  private String dateStatusChange = null;

  @SerializedName("card_number")
  private String cardNumber = null;

  @SerializedName("tran_date")
  private String tranDate = null;

  @SerializedName("reference_number")
  private String referenceNumber = null;

  @SerializedName("cb_ref_num")
  private String cbRefNum = null;

  @SerializedName("vendor_id")
  private Long vendorId = null;

  @SerializedName("purchase_id")
  private String purchaseId = null;

  public DisputeData recId(Long recId) {
    this.recId = recId;
    return this;
  }

   /**
   * Unique ID assigned by Qualpay to dispute.
   * @return recId
  **/
  @ApiModelProperty(example = "21200000002", value = "Unique ID assigned by Qualpay to dispute.")
  public Long getRecId() {
    return recId;
  }

  public void setRecId(Long recId) {
    this.recId = recId;
  }

  public DisputeData merchantId(Long merchantId) {
    this.merchantId = merchantId;
    return this;
  }

   /**
   * Unique ID assigned by Qualpay to a merchant.
   * @return merchantId
  **/
  @ApiModelProperty(example = "971000010003", value = "Unique ID assigned by Qualpay to a merchant.")
  public Long getMerchantId() {
    return merchantId;
  }

  public void setMerchantId(Long merchantId) {
    this.merchantId = merchantId;
  }

  public DisputeData incomingDate(String incomingDate) {
    this.incomingDate = incomingDate;
    return this;
  }

   /**
   * The date the dispute was issued.
   * @return incomingDate
  **/
  @ApiModelProperty(example = "2018-06-19", value = "The date the dispute was issued.")
  public String getIncomingDate() {
    return incomingDate;
  }

  public void setIncomingDate(String incomingDate) {
    this.incomingDate = incomingDate;
  }

  public DisputeData amtTran(Double amtTran) {
    this.amtTran = amtTran;
    return this;
  }

   /**
   * The amount of the original settled transaction.
   * @return amtTran
  **/
  @ApiModelProperty(example = "58.94", value = "The amount of the original settled transaction.")
  public Double getAmtTran() {
    return amtTran;
  }

  public void setAmtTran(Double amtTran) {
    this.amtTran = amtTran;
  }

  public DisputeData amtDispute(Double amtDispute) {
    this.amtDispute = amtDispute;
    return this;
  }

   /**
   * The amount of the dispute; equal to or less than the amt_tran (when in USD).
   * @return amtDispute
  **/
  @ApiModelProperty(example = "58.94", value = "The amount of the dispute; equal to or less than the amt_tran (when in USD).")
  public Double getAmtDispute() {
    return amtDispute;
  }

  public void setAmtDispute(Double amtDispute) {
    this.amtDispute = amtDispute;
  }

  public DisputeData reasonCode(String reasonCode) {
    this.reasonCode = reasonCode;
    return this;
  }

   /**
   * The card association&#39;s reason why the dispute was issued.
   * @return reasonCode
  **/
  @ApiModelProperty(example = "10.4", value = "The card association's reason why the dispute was issued.")
  public String getReasonCode() {
    return reasonCode;
  }

  public void setReasonCode(String reasonCode) {
    this.reasonCode = reasonCode;
  }

  public DisputeData reasonDesc(String reasonDesc) {
    this.reasonDesc = reasonDesc;
    return this;
  }

   /**
   * The card association&#39;s reason code desc why the dispute was issued.
   * @return reasonDesc
  **/
  @ApiModelProperty(example = "Other Fraud – Card Absent Environment", value = "The card association's reason code desc why the dispute was issued.")
  public String getReasonDesc() {
    return reasonDesc;
  }

  public void setReasonDesc(String reasonDesc) {
    this.reasonDesc = reasonDesc;
  }

  public DisputeData dataType(String dataType) {
    this.dataType = dataType;
    return this;
  }

   /**
   * The type of dispute. For all types, please refer to &lt;a href&#x3D;\&quot;/developer/api/reference#dispute-type\&quot;target&#x3D;\&quot;_blank\&quot;&gt;Dispute Type&lt;/a&gt;
   * @return dataType
  **/
  @ApiModelProperty(example = "C", value = "The type of dispute. For all types, please refer to <a href=\"/developer/api/reference#dispute-type\"target=\"_blank\">Dispute Type</a>")
  public String getDataType() {
    return dataType;
  }

  public void setDataType(String dataType) {
    this.dataType = dataType;
  }

  public DisputeData cbrWorkflow(String cbrWorkflow) {
    this.cbrWorkflow = cbrWorkflow;
    return this;
  }

   /**
   * The type of dispute workflow. For all types, please refer to &lt;a href&#x3D;\&quot;/developer/api/reference#dispute-workflow\&quot;target&#x3D;\&quot;_blank\&quot;&gt;Dispute Workflow&lt;/a&gt;
   * @return cbrWorkflow
  **/
  @ApiModelProperty(example = "A", value = "The type of dispute workflow. For all types, please refer to <a href=\"/developer/api/reference#dispute-workflow\"target=\"_blank\">Dispute Workflow</a>")
  public String getCbrWorkflow() {
    return cbrWorkflow;
  }

  public void setCbrWorkflow(String cbrWorkflow) {
    this.cbrWorkflow = cbrWorkflow;
  }

  public DisputeData status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Current Dispute Status.
   * @return status
  **/
  @ApiModelProperty(example = "N", value = "Current Dispute Status.")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public DisputeData dateStatusChange(String dateStatusChange) {
    this.dateStatusChange = dateStatusChange;
    return this;
  }

   /**
   * The date the dispute&#39;s status most recently changed.
   * @return dateStatusChange
  **/
  @ApiModelProperty(example = "2018-06-19", value = "The date the dispute's status most recently changed.")
  public String getDateStatusChange() {
    return dateStatusChange;
  }

  public void setDateStatusChange(String dateStatusChange) {
    this.dateStatusChange = dateStatusChange;
  }

  public DisputeData cardNumber(String cardNumber) {
    this.cardNumber = cardNumber;
    return this;
  }

   /**
   * The truncated card number of the dispute.
   * @return cardNumber
  **/
  @ApiModelProperty(example = "411111xxxxxx1111", value = "The truncated card number of the dispute.")
  public String getCardNumber() {
    return cardNumber;
  }

  public void setCardNumber(String cardNumber) {
    this.cardNumber = cardNumber;
  }

  public DisputeData tranDate(String tranDate) {
    this.tranDate = tranDate;
    return this;
  }

   /**
   * The date of the initial transaction.
   * @return tranDate
  **/
  @ApiModelProperty(example = "2018-02-12", value = "The date of the initial transaction.")
  public String getTranDate() {
    return tranDate;
  }

  public void setTranDate(String tranDate) {
    this.tranDate = tranDate;
  }

  public DisputeData referenceNumber(String referenceNumber) {
    this.referenceNumber = referenceNumber;
    return this;
  }

   /**
   * The bank reference number of the deposit.
   * @return referenceNumber
  **/
  @ApiModelProperty(example = "24050835204212000000011", value = "The bank reference number of the deposit.")
  public String getReferenceNumber() {
    return referenceNumber;
  }

  public void setReferenceNumber(String referenceNumber) {
    this.referenceNumber = referenceNumber;
  }

  public DisputeData cbRefNum(String cbRefNum) {
    this.cbRefNum = cbRefNum;
    return this;
  }

   /**
   * Issuer provided reference number for this transaction.
   * @return cbRefNum
  **/
  @ApiModelProperty(example = "100001", value = "Issuer provided reference number for this transaction.")
  public String getCbRefNum() {
    return cbRefNum;
  }

  public void setCbRefNum(String cbRefNum) {
    this.cbRefNum = cbRefNum;
  }

  public DisputeData vendorId(Long vendorId) {
    this.vendorId = vendorId;
    return this;
  }

   /**
   * Unique Vendor ID assigned by Qualpay to integrator.
   * @return vendorId
  **/
  @ApiModelProperty(example = "301", value = "Unique Vendor ID assigned by Qualpay to integrator.")
  public Long getVendorId() {
    return vendorId;
  }

  public void setVendorId(Long vendorId) {
    this.vendorId = vendorId;
  }

  public DisputeData purchaseId(String purchaseId) {
    this.purchaseId = purchaseId;
    return this;
  }

   /**
   * Purchase Identifier (also referred to as the invoice number generated by the merchant).
   * @return purchaseId
  **/
  @ApiModelProperty(example = "55-1212", value = "Purchase Identifier (also referred to as the invoice number generated by the merchant).")
  public String getPurchaseId() {
    return purchaseId;
  }

  public void setPurchaseId(String purchaseId) {
    this.purchaseId = purchaseId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DisputeData disputeData = (DisputeData) o;
    return Objects.equals(this.recId, disputeData.recId) &&
        Objects.equals(this.merchantId, disputeData.merchantId) &&
        Objects.equals(this.incomingDate, disputeData.incomingDate) &&
        Objects.equals(this.amtTran, disputeData.amtTran) &&
        Objects.equals(this.amtDispute, disputeData.amtDispute) &&
        Objects.equals(this.reasonCode, disputeData.reasonCode) &&
        Objects.equals(this.reasonDesc, disputeData.reasonDesc) &&
        Objects.equals(this.dataType, disputeData.dataType) &&
        Objects.equals(this.cbrWorkflow, disputeData.cbrWorkflow) &&
        Objects.equals(this.status, disputeData.status) &&
        Objects.equals(this.dateStatusChange, disputeData.dateStatusChange) &&
        Objects.equals(this.cardNumber, disputeData.cardNumber) &&
        Objects.equals(this.tranDate, disputeData.tranDate) &&
        Objects.equals(this.referenceNumber, disputeData.referenceNumber) &&
        Objects.equals(this.cbRefNum, disputeData.cbRefNum) &&
        Objects.equals(this.vendorId, disputeData.vendorId) &&
        Objects.equals(this.purchaseId, disputeData.purchaseId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(recId, merchantId, incomingDate, amtTran, amtDispute, reasonCode, reasonDesc, dataType, cbrWorkflow, status, dateStatusChange, cardNumber, tranDate, referenceNumber, cbRefNum, vendorId, purchaseId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DisputeData {\n");
    
    sb.append("    recId: ").append(toIndentedString(recId)).append("\n");
    sb.append("    merchantId: ").append(toIndentedString(merchantId)).append("\n");
    sb.append("    incomingDate: ").append(toIndentedString(incomingDate)).append("\n");
    sb.append("    amtTran: ").append(toIndentedString(amtTran)).append("\n");
    sb.append("    amtDispute: ").append(toIndentedString(amtDispute)).append("\n");
    sb.append("    reasonCode: ").append(toIndentedString(reasonCode)).append("\n");
    sb.append("    reasonDesc: ").append(toIndentedString(reasonDesc)).append("\n");
    sb.append("    dataType: ").append(toIndentedString(dataType)).append("\n");
    sb.append("    cbrWorkflow: ").append(toIndentedString(cbrWorkflow)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    dateStatusChange: ").append(toIndentedString(dateStatusChange)).append("\n");
    sb.append("    cardNumber: ").append(toIndentedString(cardNumber)).append("\n");
    sb.append("    tranDate: ").append(toIndentedString(tranDate)).append("\n");
    sb.append("    referenceNumber: ").append(toIndentedString(referenceNumber)).append("\n");
    sb.append("    cbRefNum: ").append(toIndentedString(cbRefNum)).append("\n");
    sb.append("    vendorId: ").append(toIndentedString(vendorId)).append("\n");
    sb.append("    purchaseId: ").append(toIndentedString(purchaseId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

