/*
 * Qualpay Platform API
 * This document describes the Qualpay Platform API.
 *
 * OpenAPI spec version: 1.1.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BillingCard;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * GetBillingCardsResponse
 */

public class GetBillingCardsResponse {
  @SerializedName("billing_cards")
  private List<BillingCard> billingCards = null;

  public GetBillingCardsResponse billingCards(List<BillingCard> billingCards) {
    this.billingCards = billingCards;
    return this;
  }

  public GetBillingCardsResponse addBillingCardsItem(BillingCard billingCardsItem) {
    if (this.billingCards == null) {
      this.billingCards = new ArrayList<BillingCard>();
    }
    this.billingCards.add(billingCardsItem);
    return this;
  }

   /**
   * &lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;An array of billing cards. 
   * @return billingCards
  **/
  @ApiModelProperty(value = "<br><strong>Description: </strong>An array of billing cards. ")
  public List<BillingCard> getBillingCards() {
    return billingCards;
  }

  public void setBillingCards(List<BillingCard> billingCards) {
    this.billingCards = billingCards;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetBillingCardsResponse getBillingCardsResponse = (GetBillingCardsResponse) o;
    return Objects.equals(this.billingCards, getBillingCardsResponse.billingCards);
  }

  @Override
  public int hashCode() {
    return Objects.hash(billingCards);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetBillingCardsResponse {\n");
    
    sb.append("    billingCards: ").append(toIndentedString(billingCards)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

