/*
 * Qualpay Platform API
 * This document describes the Qualpay Platform API.
 *
 * OpenAPI spec version: 1.1.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InvoicePayment;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InvoicePaymentListResponse
 */

public class InvoicePaymentListResponse {
  @SerializedName("code")
  private Integer code = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("totalPages")
  private Integer totalPages = null;

  @SerializedName("totalRecords")
  private Integer totalRecords = null;

  @SerializedName("data")
  private List<InvoicePayment> data = new ArrayList<InvoicePayment>();

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Fixed length, 1 N&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Response code from API. 0 indicates success. Refer to &lt;a href&#x3D;\&quot;/developer/api/reference#api-response-codes\&quot;target&#x3D;\&quot;_blank\&quot;&gt;Platform API Response Codes&lt;/a&gt; for entire list of return codes.
   * @return code
  **/
  @ApiModelProperty(example = "0", required = true, value = "<strong>Format: </strong>Fixed length, 1 N<br><strong>Description: </strong>Response code from API. 0 indicates success. Refer to <a href=\"/developer/api/reference#api-response-codes\"target=\"_blank\">Platform API Response Codes</a> for entire list of return codes.")
  public Integer getCode() {
    return code;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length AN&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;A short description of the API response code.
   * @return message
  **/
  @ApiModelProperty(example = "Success", required = true, value = "<strong>Format: </strong>Variable length AN<br><strong>Description: </strong>A short description of the API response code.")
  public String getMessage() {
    return message;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length N&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Total Number of pages. 
   * @return totalPages
  **/
  @ApiModelProperty(example = "10", required = true, value = "<strong>Format: </strong>Variable length N<br><strong>Description: </strong>Total Number of pages. ")
  public Integer getTotalPages() {
    return totalPages;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 3 N&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Total number of records upto a maximum of 100.
   * @return totalRecords
  **/
  @ApiModelProperty(example = "100", required = true, value = "<strong>Format: </strong>Variable length, up to 3 N<br><strong>Description: </strong>Total number of records upto a maximum of 100.")
  public Integer getTotalRecords() {
    return totalRecords;
  }

   /**
   * An array of the resource object.
   * @return data
  **/
  @ApiModelProperty(required = true, value = "An array of the resource object.")
  public List<InvoicePayment> getData() {
    return data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InvoicePaymentListResponse invoicePaymentListResponse = (InvoicePaymentListResponse) o;
    return Objects.equals(this.code, invoicePaymentListResponse.code) &&
        Objects.equals(this.message, invoicePaymentListResponse.message) &&
        Objects.equals(this.totalPages, invoicePaymentListResponse.totalPages) &&
        Objects.equals(this.totalRecords, invoicePaymentListResponse.totalRecords) &&
        Objects.equals(this.data, invoicePaymentListResponse.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, message, totalPages, totalRecords, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InvoicePaymentListResponse {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    totalPages: ").append(toIndentedString(totalPages)).append("\n");
    sb.append("    totalRecords: ").append(toIndentedString(totalRecords)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

