/*
 * Qualpay Platform API
 * This document describes the Qualpay Platform API.
 *
 * OpenAPI spec version: 1.1.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * LineItem
 */

public class LineItem {
  @SerializedName("quantity")
  private Integer quantity = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("unit_cost")
  private Double unitCost = null;

  public LineItem quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 3 N&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;The count of items.
   * @return quantity
  **/
  @ApiModelProperty(example = "10", required = true, value = "<strong>Format: </strong>Variable length, up to 3 N<br><strong>Description: </strong>The count of items.")
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public LineItem description(String description) {
    this.description = description;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length AN&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Description of the item.
   * @return description
  **/
  @ApiModelProperty(example = "Pencils", required = true, value = "<strong>Format: </strong>Variable length AN<br><strong>Description: </strong>Description of the item.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public LineItem unitCost(Double unitCost) {
    this.unitCost = unitCost;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 8,2 AN&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Cost per unit, up to 2 decimal places.
   * @return unitCost
  **/
  @ApiModelProperty(example = "1.49", required = true, value = "<strong>Format: </strong>Variable length, up to 8,2 AN<br><strong>Description: </strong>Cost per unit, up to 2 decimal places.")
  public Double getUnitCost() {
    return unitCost;
  }

  public void setUnitCost(Double unitCost) {
    this.unitCost = unitCost;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LineItem lineItem = (LineItem) o;
    return Objects.equals(this.quantity, lineItem.quantity) &&
        Objects.equals(this.description, lineItem.description) &&
        Objects.equals(this.unitCost, lineItem.unitCost);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quantity, description, unitCost);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LineItem {\n");
    
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    unitCost: ").append(toIndentedString(unitCost)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

