/*
 * Qualpay Platform API
 * This document describes the Qualpay Platform API.
 *
 * OpenAPI spec version: 1.1.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Payment
 */

public class Payment {
  @SerializedName("card_type")
  private String cardType = null;

  @SerializedName("currency")
  private List<String> currency = null;

  public Payment cardType(String cardType) {
    this.cardType = cardType;
    return this;
  }

   /**
   * The two character abbreviation for the card type.
   * @return cardType
  **/
  @ApiModelProperty(example = "VS", value = "The two character abbreviation for the card type.")
  public String getCardType() {
    return cardType;
  }

  public void setCardType(String cardType) {
    this.cardType = cardType;
  }

  public Payment currency(List<String> currency) {
    this.currency = currency;
    return this;
  }

  public Payment addCurrencyItem(String currencyItem) {
    if (this.currency == null) {
      this.currency = new ArrayList<String>();
    }
    this.currency.add(currencyItem);
    return this;
  }

   /**
   * An array of currency codes allowed for the specified card type.
   * @return currency
  **/
  @ApiModelProperty(example = "\"[840,124]\"", value = "An array of currency codes allowed for the specified card type.")
  public List<String> getCurrency() {
    return currency;
  }

  public void setCurrency(List<String> currency) {
    this.currency = currency;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Payment payment = (Payment) o;
    return Objects.equals(this.cardType, payment.cardType) &&
        Objects.equals(this.currency, payment.currency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cardType, currency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Payment {\n");
    
    sb.append("    cardType: ").append(toIndentedString(cardType)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

