/*
 * Qualpay Platform API
 * This document describes the Qualpay Platform API.
 *
 * OpenAPI spec version: 1.1.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SetPrimaryShippingAddressRequest
 */

public class SetPrimaryShippingAddressRequest {
  @SerializedName("shipping_id")
  private Long shippingId = null;

  @SerializedName("merchant_id")
  private Long merchantId = null;

  public SetPrimaryShippingAddressRequest shippingId(Long shippingId) {
    this.shippingId = shippingId;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 10 N&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Shipping ID that should be set as the primary shipping address. The shipping id should belong to the customer. 
   * @return shippingId
  **/
  @ApiModelProperty(example = "12345", required = true, value = "<strong>Format: </strong>Variable length, up to 10 N<br><strong>Description: </strong>Shipping ID that should be set as the primary shipping address. The shipping id should belong to the customer. ")
  public Long getShippingId() {
    return shippingId;
  }

  public void setShippingId(Long shippingId) {
    this.shippingId = shippingId;
  }

  public SetPrimaryShippingAddressRequest merchantId(Long merchantId) {
    this.merchantId = merchantId;
    return this;
  }

   /**
   * &lt;strong&gt;Format: &lt;/strong&gt;Variable length, up to 16 AN&lt;br&gt;&lt;strong&gt;Description: &lt;/strong&gt;Identifies the merchant to whom this request applies. Optional field, applicable only if the request is sent on behalf of another merchant.&lt;br&gt;&lt;strong&gt;Conditional Requirement: &lt;/strong&gt;Required if this request is on behalf of another merchant.
   * @return merchantId
  **/
  @ApiModelProperty(example = "210000000289", value = "<strong>Format: </strong>Variable length, up to 16 AN<br><strong>Description: </strong>Identifies the merchant to whom this request applies. Optional field, applicable only if the request is sent on behalf of another merchant.<br><strong>Conditional Requirement: </strong>Required if this request is on behalf of another merchant.")
  public Long getMerchantId() {
    return merchantId;
  }

  public void setMerchantId(Long merchantId) {
    this.merchantId = merchantId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SetPrimaryShippingAddressRequest setPrimaryShippingAddressRequest = (SetPrimaryShippingAddressRequest) o;
    return Objects.equals(this.shippingId, setPrimaryShippingAddressRequest.shippingId) &&
        Objects.equals(this.merchantId, setPrimaryShippingAddressRequest.merchantId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shippingId, merchantId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SetPrimaryShippingAddressRequest {\n");
    
    sb.append("    shippingId: ").append(toIndentedString(shippingId)).append("\n");
    sb.append("    merchantId: ").append(toIndentedString(merchantId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

